services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: time_tracker_backend
    restart: always
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_URI=${MONGO_URI}
    networks:
      - app_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: time_tracker_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
